from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ProjectStatus(StrEnum):
    DRAFT_CREATED = "DRAFT_CREATED"
    DOCUMENT_GENERATING = "DOCUMENT_GENERATING"
    DOCUMENT_DRAFTED = "DOCUMENT_DRAFTED"
    DOCUMENT_REVIEW_PENDING = "DOCUMENT_REVIEW_PENDING"
    DOCUMENT_CHANGE_REQUESTED = "DOCUMENT_CHANGE_REQUESTED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_APPROVED = "DOCUMENT_APPROVED"
    BLUEPRINT_GENERATING = "BLUEPRINT_GENERATING"
    BLUEPRINT_GENERATED = "BLUEPRINT_GENERATED"
    BLUEPRINT_VALIDATION_FAILED = "BLUEPRINT_VALIDATION_FAILED"
    BLUEPRINT_VALIDATED = "BLUEPRINT_VALIDATED"
    IMPLEMENTATION_GENERATING = "IMPLEMENTATION_GENERATING"
    IMPLEMENTATION_FAILED = "IMPLEMENTATION_FAILED"
    IMPLEMENTATION_GENERATED = "IMPLEMENTATION_GENERATED"
    IMPLEMENTATION_REVIEW_PENDING = "IMPLEMENTATION_REVIEW_PENDING"
    IMPLEMENTATION_APPROVED = "IMPLEMENTATION_APPROVED"
    READY_FOR_DEPLOY = "READY_FOR_DEPLOY"
    DEPLOYED = "DEPLOYED"


class ProjectCreate(BaseModel):
    name: str = Field(min_length=1, max_length=200)
    description: str = Field(default="", max_length=2000)


class ProjectRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    name: str
    description: str
    status: ProjectStatus
    created_at: datetime
    updated_at: datetime
